{
    data: [
           {
               "id": 1,
               "name": "Snorkel",
               "picture": "https://www.sicssalab.net/contenido/lugares-de-experiencia/1-quintana-roo/nautico-1/avatar.jpeg",
               "profileCover": "https://www.sicssalab.net/contenido/lugares-de-experiencia/1-quintana-roo/nautico-1/perfil.jpeg",
               "members": "18k",
               "category": "Náutico",
               "type": "Publico",
               "content": [
                   {
                       "id": 1,
                       "picture": "https://www.sicssalab.net/contenido/lugares-de-experiencia/1-quintana-roo/nautico-1/avatar.jpeg",
                       "createDate": "3min",
                       "name": "Snorkel",
                       "likes": 367,
                       "videos": [
                           "https://www.sicssalab.net/contenido/lugares-de-experiencia/1-quintana-roo/nautico-1/1.mp4"
                       ],
                       "comments": [
                           {
                               "id": 1,
                               "userName": "Cloe Weissnat",
                               "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/beautiful-woman-red-hair-in-frame-circular-avatar-character-free-vector.webp",
                               "comment": " Definitivamente la mejor actividad acuática",
                               "createDate": "2seg"
                           },
                           {
                               "id": 2,
                               "userName": "Henrry Graham",
                               "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/5556512.png",
                               "comment": "Te recargas de energia con esta actividad XD",
                               "createDate": "1hr"
                           },
                           {
                               "id": 3,
                               "userName": "Nicholas Thomson",
                               "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/5556549.png",
                               "comment": "¡Que increible, me divertí mucho",
                               "createDate": "4hrs"
                           },
                         
                       ]
                   },
                   {
                       "id": 2,
                       "picture": "https://www.sicssalab.net/contenido/lugares-de-experiencia/1-quintana-roo/nautico-1/avatar.jpeg",
                       "createDate": "5hrs",
                       "name": "Snorkel",
                       "likes": 482,
                       "videos": [
                           "https://www.sicssalab.net/contenido/lugares-de-experiencia/1-quintana-roo/nautico-1/2.mp4"
                       ],
                       "comments": [
                           {
                               "id": 1,
                               "userName": "Cloe Weissnat",
                               "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/beautiful-woman-red-hair-in-frame-circular-avatar-character-free-vector.webp",
                               "comment": "Si quieres una nueva experiencia acuática esta es una excelente opción",
                               "createDate": "2seg"
                           },
                           {
                               "id": 2,
                               "userName": "Henrry Graham",
                               "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/5556512.png",
                               "comment": "Me gusta, se ve divertido",
                               "createDate": "1hr"
                           },
                           {
                               "id": 3,
                               "userName": "Nicholas Thomson",
                               "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/5556549.png",
                               "comment": "¡Definitivamente tengo que ir!",
                               "createDate": "4hrs"
                           },
                         
                       ]
                       
                   }
               ]
           },
            {
                "id": 2,
                "name": "Las Trajineras",
                "picture": "https://www.sicssalab.net/contenido/lugares-de-experiencia/2-mexico/nautico-1/avatar.jpg",
                "profileCover": "https://www.sicssalab.net/contenido/lugares-de-experiencia/2-mexico/nautico-1/perfil.jpg",
                "members": "18k",
                "category": "Náutico",
                "type": "Publico",
                "content": [
                    {
                        "id": 1,
                        "picture": "https://www.sicssalab.net/contenido/lugares-de-experiencia/2-mexico/nautico-1/avatar.jpg",
                        "createDate": "3min",
                        "name": "Las Trajineras",
                        "likes": 367,
                        "videos": [
                            "https://www.sicssalab.net/contenido/lugares-de-experiencia/2-mexico/nautico-1/1.mp4"
                        ],
                        "comments": [
                            {
                                "id": 1,
                                "userName": "Cloe Weissnat",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/beautiful-woman-red-hair-in-frame-circular-avatar-character-free-vector.webp",
                                "comment": " Definitivamente la mejor actividad acuática",
                                "createDate": "2seg"
                            },
                            {
                                "id": 2,
                                "userName": "Henrry Graham",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/5556512.png",
                                "comment": "Te recargas de energia con esta actividad XD",
                                "createDate": "1hr"
                            },
                            {
                                "id": 3,
                                "userName": "Nicholas Thomson",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/5556549.png",
                                "comment": "¡Que increible, me divertí mucho",
                                "createDate": "4hrs"
                            },
                          
                        ]
                    },
                    {
                        "id": 2,
                        "picture": "https://www.sicssalab.net/contenido/lugares-de-experiencia/2-mexico/nautico-1/avatar.jpg",
                        "createDate": "5hrs",
                        "name": "Las Trajineras",
                        "likes": 482,
                        "videos": [
                            "https://www.sicssalab.net/contenido/lugares-de-experiencia/2-mexico/nautico-1/2.mp4"
                        ],
                        "comments": [
                            {
                                "id": 1,
                                "userName": "Cloe Weissnat",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/beautiful-woman-red-hair-in-frame-circular-avatar-character-free-vector.webp",
                                "comment": "Si quieres una nueva experiencia acuática esta es una excelente opción",
                                "createDate": "2seg"
                            },
                            {
                                "id": 2,
                                "userName": "Henrry Graham",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/5556512.png",
                                "comment": "Me gusta, se ve divertido",
                                "createDate": "1hr"
                            },
                            {
                                "id": 3,
                                "userName": "Nicholas Thomson",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/5556549.png",
                                "comment": "¡Definitivamente tengo que ir!",
                                "createDate": "4hrs"
                            },
                          
                        ]
                        
                    }
                ]
            },
            {
                "id": 3,
                "name": "La Banana",
                "picture": "https://www.sicssalab.net/contenido/lugares-de-experiencia/12-guerrero/nautico-1/avatar.jpg",
                "profileCover": "https://www.sicssalab.net/contenido/lugares-de-experiencia/12-guerrero/nautico-1/perfil.jpg",
                "members": "18k",
                "category": "Náutico",
                "type": "Publico",
                "content": [
                    {
                        "id": 1,
                        "picture": "https://www.sicssalab.net/contenido/lugares-de-experiencia/12-guerrero/nautico-1/avatar.jpg",
                        "createDate": "3min",
                        "name": "La Banana",
                        "likes": 367,
                        "videos": [
                            "https://www.sicssalab.net/contenido/lugares-de-experiencia/12-guerrero/nautico-1/1.mp4"
                        ],
                        "comments": [
                            {
                                "id": 1,
                                "userName": "Cloe Weissnat",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/beautiful-woman-red-hair-in-frame-circular-avatar-character-free-vector.webp",
                                "comment": " Definitivamente la mejor actividad acuática",
                                "createDate": "2seg"
                            },
                            {
                                "id": 2,
                                "userName": "Henrry Graham",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/5556512.png",
                                "comment": "Te recargas de energia con esta actividad XD",
                                "createDate": "1hr"
                            },
                            {
                                "id": 3,
                                "userName": "Nicholas Thomson",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/5556549.png",
                                "comment": "¡Que increible, me divertí mucho",
                                "createDate": "4hrs"
                            },
                          
                        ]
                    },
                    {
                        "id": 2,
                        "picture": "https://www.sicssalab.net/contenido/lugares-de-experiencia/12-guerrero/nautico-1/avatar.jpg",
                        "createDate": "5hrs",
                        "name": "La Banana",
                        "likes": 482,
                        "videos": [
                            "https://www.sicssalab.net/contenido/lugares-de-experiencia/12-guerrero/nautico-1/2.mp4"
                        ],
                        "comments": [
                            {
                                "id": 1,
                                "userName": "Cloe Weissnat",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/beautiful-woman-red-hair-in-frame-circular-avatar-character-free-vector.webp",
                                "comment": "Si quieres una nueva experiencia acuática esta es una excelente opción",
                                "createDate": "2seg"
                            },
                            {
                                "id": 2,
                                "userName": "Henrry Graham",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/5556512.png",
                                "comment": "Me gusta, se ve divertido",
                                "createDate": "1hr"
                            },
                            {
                                "id": 3,
                                "userName": "Nicholas Thomson",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/5556549.png",
                                "comment": "¡Definitivamente tengo que ir!",
                                "createDate": "4hrs"
                            },
                          
                        ]
                        
                    }
                ]
            },
            {
                "id": 4,
                "name": "Kayac",
                "picture": "https://www.sicssalab.net/contenido/lugares-de-experiencia/13-baja-california/nautico-1/avatar.jpg",
                "profileCover": "https://www.sicssalab.net/contenido/lugares-de-experiencia/13-baja-california/nautico-1/perfil.jpg",
                "members": "18k",
                "category": "Náutico",
                "type": "Publico",
                "content": [
                    {
                        "id": 1,
                        "picture": "https://www.sicssalab.net/contenido/lugares-de-experiencia/13-baja-california/nautico-1/avatar.jpg",
                        "createDate": "3min",
                        "name": "Kayac",
                        "likes": 367,
                        "videos": [
                            "https://www.sicssalab.net/contenido/lugares-de-experiencia/13-baja-california/nautico-1/1.mp4"
                        ],
                        "comments": [
                            {
                                "id": 1,
                                "userName": "Cloe Weissnat",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/beautiful-woman-red-hair-in-frame-circular-avatar-character-free-vector.webp",
                                "comment": " Definitivamente la mejor actividad acuática",
                                "createDate": "2seg"
                            },
                            {
                                "id": 2,
                                "userName": "Henrry Graham",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/5556512.png",
                                "comment": "Te recargas de energia con esta actividad XD",
                                "createDate": "1hr"
                            },
                            {
                                "id": 3,
                                "userName": "Nicholas Thomson",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/5556549.png",
                                "comment": "¡Que increible, me divertí mucho",
                                "createDate": "4hrs"
                            },
                          
                        ]
                    },
                    {
                        "id": 2,
                        "picture": "https://www.sicssalab.net/contenido/lugares-de-experiencia/13-baja-california/nautico-1/avatar.jpg",
                        "createDate": "5hrs",
                        "name": "Kayac",
                        "likes": 482,
                        "videos": [
                            "https://www.sicssalab.net/contenido/lugares-de-experiencia/13-baja-california/nautico-1/2.mp4"
                        ],
                        "comments": [
                            {
                                "id": 1,
                                "userName": "Cloe Weissnat",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/beautiful-woman-red-hair-in-frame-circular-avatar-character-free-vector.webp",
                                "comment": "Si quieres una nueva experiencia acuática esta es una excelente opción",
                                "createDate": "2seg"
                            },
                            {
                                "id": 2,
                                "userName": "Henrry Graham",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/5556512.png",
                                "comment": "Me gusta, se ve divertido",
                                "createDate": "1hr"
                            },
                            {
                                "id": 3,
                                "userName": "Nicholas Thomson",
                                "picture": "https://social-network.sicssa-lab.com/assets/images/avatars/5556549.png",
                                "comment": "¡Definitivamente tengo que ir!",
                                "createDate": "4hrs"
                            },
                          
                        ]
                        
                    }
                ]
            }     
       ]
   }